## Stock prices

---
* author:  [Prasert Kanawattanachai](prasert.k@chula.ac.th)
* YouTube: https://www.youtube.com/prasertcbs
* github: https://github.com/prasertcbs/
* [Chulalongkorn Business School](https://www.cbs.chula.ac.th/en/)
---

In [1]:
import pandas as pd
import numpy as np
import pandas as pd
from pandas_datareader import data as pdr

In [2]:
print(f"pandas  version: {pd.__version__}")
pd.Timestamp.now()

pandas  version: 1.5.2

Timestamp('2023-01-03 20:41:54.984866')

## read historical stock prices

In [2]:
import yfinance as yf
dat = yf.download(["MSFT", "AAPL", "GOOG"], start="2022-12-01", end="2022-12-07")
# dat = yf.download("MSFT AAPL GOOG", start="2022-12-01", end="2022-12-07")
dat

[*********************100%***********************]  3 of 3 completed

             Adj Close                               Close              \
                  AAPL        GOOG        MSFT        AAPL        GOOG
Date
2022-12-01  148.309998  101.279999  254.690002  148.309998  101.279999
2022-12-02  147.809998  100.830002  255.020004  147.809998  100.830002
2022-12-05  146.630005   99.870003  250.199997  146.630005   99.870003
2022-12-06  142.910004   97.309998  245.119995  142.910004   97.309998

                              High                                 Low  \
                  MSFT        AAPL        GOOG        MSFT        AAPL
Date
2022-12-01  254.690002  149.130005  102.589996  256.119995  146.610001
2022-12-02  255.020004  148.000000  101.150002  256.059998  145.649994
2022-12-05  250.199997  150.919998  101.750000  253.820007  145.770004
2022-12-06  245.119995  147.300003  100.209999  251.860001  141.919998

                                          Open                          \
                  GOOG        MSFT        AAPL        GOOG        MSFT
Date
2022-12-01  100.669998  250.919998  148.210007  101.400002  253.869995
2022-12-02   99.169998  249.690002  145.960007   99.370003  249.820007
2022-12-05   99.355003  248.059998  147.770004   99.815002  252.009995
2022-12-06   96.760002  243.779999  147.070007   99.669998  250.820007

              Volume
                AAPL      GOOG      MSFT
Date
2022-12-01  71250400  21771500  26041500
2022-12-02  65447400  18812200  21528500
2022-12-05  68826400  19955500  23435300
2022-12-06  64727200  20877600  22463700

In [3]:
df=dat.stack().reset_index().set_index('Date')
df.rename(columns={'level_1':'Symbol'}, inplace=True)
df

,Symbol,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,,
2022-12-01,AAPL,148.309998,148.309998,149.130005,146.610001,148.210007,71250400
2022-12-01,GOOG,101.279999,101.279999,102.589996,100.669998,101.400002,21771500
2022-12-01,MSFT,254.690002,254.690002,256.119995,250.919998,253.869995,26041500
2022-12-02,AAPL,147.809998,147.809998,148.000000,145.649994,145.960007,65447400
2022-12-02,GOOG,100.830002,100.830002,101.150002,99.169998,99.370003,18812200
2022-12-02,MSFT,255.020004,255.020004,256.059998,249.690002,249.820007,21528500
2022-12-05,AAPL,146.630005,146.630005,150.919998,145.770004,147.770004,68826400
2022-12-05,GOOG,99.870003,99.870003,101.750000,99.355003,99.815002,19955500
2022-12-05,MSFT,250.199997,250.199997,253.820007,248.059998,252.009995,23435300
2022-12-06,AAPL,142.910004,142.910004,147.300003,141.919998,147.070007,64727200
2022-12-06,GOOG,97.309998,97.309998,100.209999,96.760002,99.669998,20877600
2022-12-06,MSFT,245.119995,245.119995,251.860001,243.779999,250.820007,22463700

In [4]:
df

,Symbol,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,,
2022-12-01,AAPL,148.309998,148.309998,149.130005,146.610001,148.210007,71250400
2022-12-01,GOOG,101.279999,101.279999,102.589996,100.669998,101.400002,21771500
2022-12-01,MSFT,254.690002,254.690002,256.119995,250.919998,253.869995,26041500
2022-12-02,AAPL,147.809998,147.809998,148.000000,145.649994,145.960007,65447400
2022-12-02,GOOG,100.830002,100.830002,101.150002,99.169998,99.370003,18812200
2022-12-02,MSFT,255.020004,255.020004,256.059998,249.690002,249.820007,21528500
2022-12-05,AAPL,146.630005,146.630005,150.919998,145.770004,147.770004,68826400
2022-12-05,GOOG,99.870003,99.870003,101.750000,99.355003,99.815002,19955500
2022-12-05,MSFT,250.199997,250.199997,253.820007,248.059998,252.009995,23435300
2022-12-06,AAPL,142.910004,142.910004,147.300003,141.919998,147.070007,64727200
2022-12-06,GOOG,97.309998,97.309998,100.209999,96.760002,99.669998,20877600
2022-12-06,MSFT,245.119995,245.119995,251.860001,243.779999,250.820007,22463700

In [5]:
df.to_csv('my port.csv', index=True)